# Build and test .NET Core projects
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'WPFSamples*.sln'
  buildPlatform: 'Mixed Platforms'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: "Install .NET Core SDK"
  inputs:
    script: '$(Build.SourcesDirectory)\eng\Install-Latest-DotnetCore3.ps1'
    arguments: -v 3.0.100-preview6-012264


- task: VSBuild@1
  displayName: "Restore NuGet Packages"
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:SkipInvalidConfigurations=true /t:Restore'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: "Build Solutions"
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:SkipInvalidConfigurations=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

